# Generated by Django 2.1.2 on 2018-10-22 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('type', models.CharField(default='MultipleChoice', max_length=20, verbose_name='Type')),
                ('active', models.BooleanField(default=False)),
                ('avgVote', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('voteCount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=10, verbose_name='Room ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=20, verbose_name='vote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Room'),
        ),
    ]
