# Generated by Django 2.1.2 on 2018-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous',
            field=models.BooleanField(default=None, verbose_name='anonymous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='private',
            field=models.BooleanField(default=None, verbose_name='private'),
            preserve_default=False,
        ),
    ]
