# Generated by Django 2.1.2 on 2018-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181022_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, default=None, max_length=200, verbose_name='option')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Option'),
            preserve_default=False,
        ),
    ]
