# Generated by Django 2.1.2 on 2018-10-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181024_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
