# Generated by Django 2.1.2 on 2018-10-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181024_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcvote',
            old_name='option',
            new_name='vote',
        ),
    ]
