# Generated by Django 2.1.2 on 2018-10-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181025_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcvote',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='numberedvote',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='yesnovote',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
