# Generated by Django 2.1.2 on 2018-11-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_numberedvote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='private',
        ),
        migrations.AddField(
            model_name='room',
            name='anonymous',
            field=models.BooleanField(default=None, verbose_name='anonymous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
