# Generated by Django 2.1.2 on 2018-11-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
