# Generated by Django 2.1.2 on 2018-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181107_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
